apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubereboot.github.io/charts'
    targetRevision: 5.2.0
    chart: kured
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
